AWSTemplateFormatVersion: '2010-09-09'
Description: 'sam-app Sample SAM Template for sam-app

  '
Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Role:
        Ref: CodeDeployRole
      Type: Canary10Percent5Minutes
Metadata:
  AWS::ServerlessRepo::Application:
    Author: Joe Norman
    Description: This application analyzes Zendesk tickets for negative sentiment,
      tags them as 'negative' and applies a customizable escalation time frame. It
      also translates tickets, finds keywords, and sends them to S3 for analysis.
    HomePageUrl: https://github.com/joe-norman/eventbridge-zendesk
    Labels:
    - zendesk
    - moderation
    - sentiment
    - lambda
    - eventbridge
    - comprehend
    LicenseUrl: s3://nojosep-sam/c4237cb282e57ea03a579d66a652cb3f
    Name: Zendesk-AWS-EventBridge
    ReadmeUrl: s3://nojosep-sam/faeb4756d848fb57353531a0c2c4dcd9
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/joe-norman/eventbridge-zendesk
    SpdxLicenseId: MIT-0
  EventSourceName:
    Default: ''
    Description: The event source name generated by the Zendesk connector
    Type: String
  S3BucketAnalytics:
    Default: ''
    Description: S3 bucket name for dropping data used in Analytics
    Type: String
  SLAHighWait:
    Default: 120
    Description: High priority SLA wait time in seconds
    Type: String
  SLANormalWait:
    Default: 120
    Description: Normal priority SLA wait time in seconds
    Type: String
  SLAUrgentWait:
    Default: 120
    Description: Urgent priority SLA wait time in seconds
    Type: String
  ZenDeskDomainKey:
    Default: ZenDeskDomain
    Description: Your Unique Zendesk Domain name (excluding https:// and .com)
    Type: AWS::SSM::Parameter::Value<String>
  ZenDeskTokenKey:
    Default: ZenDeskToken
    Description: Your API Token
    Type: AWS::SSM::Parameter::Value<String>
  ZenDeskUsernameKey:
    Default: ZenDeskUsername
    Description: Your agent username that will connect to the Zedesk API - email
    Type: AWS::SSM::Parameter::Value<String>
Resources:
  MyEventsRule:
    DependsOn:
    - ZendeskEventBus
    - ZendDemoStateMachine
    - MyStatesExecutionRole
    Properties:
      Description: Events Rule with StepFunctionParams
      EventBusName:
        Ref: EventSourceName
      EventPattern:
        account:
        - Ref: AWS::AccountId
        detail-type:
        - 'Support Ticket: Ticket Created'
      Targets:
      - Arn: '!Ref ZendDemoStateMachine'
        Id: NewTicketSFN
        RoleArn: "Fn::GetAtt:\n  - MyStatesExecutionRole\n  - Arn"
    Type: AWS::Events::Rule
  MyLambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
      ManagedPolicyArns:
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/ComprehendFullAccess
      Path: /
      RoleName:
        Fn::Sub: CodeStar-${ProjectId}-Execution${Stage}
    Type: AWS::IAM::Role
  MyStatesExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - Fn::Sub: states.${AWS::Region}.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - lambda:InvokeFunction
            - comprehend:DetectSentiment
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: StatesExecutionPolicy
    Type: AWS::IAM::Role
  MyTranslateTextExecutionRole:
    Description: Lambda role for Translate Text function
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
      ManagedPolicyArns:
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/TranslateFullAccess
      Path: /
      RoleName:
        Fn::Sub: CodeStar-${ProjectId}-Execution${Stage}-TranslateTextLambdaRole
    Type: AWS::IAM::Role
  MyWriteToS3ExecutionRole:
    Description: Lambda service role to write to Analytics S3 Bucket
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          ManagedPolicyArns:
          - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          Path: /
          Policies:
          - PolicyDocument:
              Statement:
              - Action:
                - s3:PutObject
                Effect: Allow
                Resource:
                  Fn::Sub: arn:aws:s3:::$(S3BucketAnalytics)/*
              Version: '2012-10-17'
            PolicyName: WriteToS3ExecutionPolicy
          Principal:
            Service:
            - lambda.amazonaws.com
      RoleName:
        Fn::Sub: CodeStar-${ProjectId}-Execution${Stage}-WriteToS3LambdaRole
    Type: AWS::IAM::Role
  ZenDeskDemoGetFullTicket:
    Properties:
      CodeUri: s3://nojosep-sam/1e5accdb0c28bae7b5fdce61f662278d
      Environment:
        Variables:
          ZenDeskDomain:
            Ref: ZenDeskDomainKey
          ZenDeskPassword:
            Ref: ZenDeskTokenKey
          ZenDeskUsername:
            Ref: ZenDeskUsernameKey
      Handler: getFullTicket.handler
      Role:
        Fn::GetAtt:
        - MyLambdaExecutionRole
        - Arn
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  ZenDeskDemoGetSentiment:
    Properties:
      CodeUri: s3://nojosep-sam/81bf993b3c0da0e23a70c9ad65b755b2
      Environment: null
      Handler: getSentiment.handler
      Role:
        Fn::GetAtt:
        - MyLambdaExecutionRole
        - Arn
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  ZenDeskDemoSetPriority:
    Properties:
      CodeUri: s3://nojosep-sam/d1a589d38d53856203f6c6705bdae3a5
      Environment:
        Variables:
          ZenDeskDomain:
            Ref: ZenDeskDomainKey
          ZenDeskPassword:
            Ref: ZenDeskTokenKey
          ZenDeskUsername:
            Ref: ZenDeskUsernameKey
      Handler: setPriority.handler
      Role:
        Fn::GetAtt:
        - MyLambdaExecutionRole
        - Arn
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  ZenDeskDemoSetTags:
    Properties:
      CodeUri: s3://nojosep-sam/76b3c26894f91ad1e12edd6c2702f14a
      Environment:
        Variables:
          ZenDeskDomain:
            Ref: ZenDeskDomainKey
          ZenDeskPassword:
            Ref: ZenDeskTokenKey
          ZenDeskUsername:
            Ref: ZenDeskUsernameKey
      Handler: setTags.handler
      Role:
        Fn::GetAtt:
        - MyLambdaExecutionRole
        - Arn
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  ZenDeskDemoTranslateTicket:
    Properties:
      CodeUri: s3://nojosep-sam/edb6e7538f5d76f70830c09988d5b2b4
      Handler: translateTicket.handler
      Role:
        Fn::GetAtt:
        - MyTranslateTextExecutionRole
        - Arn
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  ZenDeskWriteToS3:
    Properties:
      CodeUri: s3://nojosep-sam/3dfbb5e572ceaa776324782b44c627ba
      Environment:
        Variables:
          S3BucketAnalytics:
            Ref: S3BucketAnalytics
      Handler: writeToS3.handler
      Role:
        Fn::GetAtt:
        - MyWriteToS3ExecutionRole
        - Arn
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  ZendDemoStateMachine:
    Properties:
      DefinitionString:
        Fn::Sub: "{\n   \"Comment\": \"Understand the ticket sentiment, apply tags\
          \ and check back when answered to ensure SLA's are met\",\n   \"StartAt\"\
          : \"FullTicketInfo\",\n   \"States\": {\n\n     \"FullTicketInfo\": {\n\
          \       \"Type\" : \"Task\",\n       \"Resource\": \"${ZenDeskDemoGetFullTicket.Arn}\"\
          ,\n       \"InputPath\":  \"$.detail.ticket_event.ticket\",\n       \"ResultPath\"\
          : \"$\",\n       \"Next\": \"TranslateTicket\"\n     },\n     \n     \"\
          TranslateTicket\": {\n        \"Type\": \"Task\",\n        \"Resource\"\
          : \"${ZenDeskDemoTranslateTicket.Arn\",\n        \"InputPath\": \"$\",\n\
          \        \"ResultPath\": \"$\",\n        \"OutputPath\": \"$\",\n      \
          \  \"Next\": \"GetTopics\"\n     },\n     \n     \"GetTopics\": {\n    \
          \    \"Type\": \"Task\",\n        \"Resource\": \"${ZenDeskDemoGetTopics.Arn\"\
          ,\n        \"InputPath\": \"$\",\n        \"ResultPath\": \"$.topics\",\n\
          \        \"OutputPath\": \"$\",\n        \"Next\": \"GetSentiment\"\n  \
          \   },\n\n     \"GetSentiment\": {\n       \"Type\": \"Task\",\n       \"\
          Resource\": \"${ZenDeskDemoGetSentiment.Arn}\",\n       \"InputPath\": \"\
          $.raw_subject\",\n       \"ResultPath\": \"$.sentiment\",\n       \"OutputPath\"\
          : \"$\",\n       \"Next\": \"WriteToS3\"\n     },\n     \n     \"WriteToS3\"\
          : {\n       \"Type\": Task\",\n       \"Resource\": \"${ZenDeskDemoWriteToS3.Arn}\"\
          ,\n       \"InputPath\": \"$\",\n       \"ResultPath\": \"$.sentToAnalytics\"\
          ,\n       \"OutputPath\": \"$\",\n       \"Next\": \"isNegative\"\n    \
          \ },\n\n     \"isNegative\": {\n       \"Type\" : \"Choice\",\n       \"\
          Choices\": [\n         {\n           \"Variable\": \"$.sentiment.Sentiment\"\
          ,\n           \"StringEquals\": \"NEGATIVE\",\n           \"Next\": \"FullTicketInfo\"\
          \n         }\n       ],\n       \"Default\": \"ClosedOrNotNegative\"\n \
          \    },\n \n     \"setTags\": {\n       \"Type\" : \"Task\",\n       \"\
          Resource\": \"${ZenDeskDemoSetTags.Arn}\",\n       \"ResultPath\": \"$.tags\"\
          ,\n       \"OutputPath\": \"$\",\n       \"Next\": \"isClosed\"\n     },\n\
          \     \n     \n  \"GetSLAWaitTime\": {\n       \"Type\" : \"Choice\",\n\
          \       \"Choices\": [\n         {\n           \"Variable\": \"$.priority\"\
          ,\n           \"StringEquals\": \"normal\",\n           \"Next\": \"SLAHighWait\"\
          \n         },\n         {\n           \"Variable\": \"$.priority\",\n  \
          \         \"StringEquals\": \"high\",\n           \"Next\": \"SLAUrgentWait\"\
          \n         },\n         {\n           \"Variable\": \"$.priority\",\n  \
          \         \"StringEquals\": \"urgent\",\n           \"Next\": \"FinalEscalationState\"\
          \n         }\n       ],\n        \"Default\": \"SLANormalWait\"\n      \
          \  \n     },\n     \n    \"FinalEscalationState\": {\n            \"Comment\"\
          \ : \"Ticket cannot be escalated further\",\n            \"Type\": \"Succeed\"\
          \n        },\n     \n     \"EscalatePriority\": {\n         \"Type\" : \"\
          Task\",\n         \"Resource\": \"${ZenDeskDemoSetPriority.Arn}\",\n   \
          \      \"InputPath\":  \"$\",\n         \"ResultPath\": \"$\",\n       \
          \  \"Next\": \"isClosed\"\n     },\n\n     \"SLANormalWait\": {\n      \
          \   \"Type\": \"Wait\",\n         \"Seconds\": ${SLANormalWait},\n     \
          \    \"Next\": \"EscalatePriority\"\n       },\n       \n       \"SLAHighWait\"\
          : {\n         \"Type\": \"Wait\",\n         \"Seconds\": ${SLAHighWait},\n\
          \         \"Next\": \"EscalatePriority\"\n       },\n       \n       \n\
          \       \"SLAUrgentWait\": {\n         \"Type\": \"Wait\",\n         \"\
          Seconds\":${SLAUrgentWait},\n         \"Next\": \"EscalatePriority\"\n \
          \      },\n\n     \"isClosed\": {\n       \"Type\" : \"Choice\",\n     \
          \  \"Choices\": [\n         {\n           \"Variable\": \"$.status\",\n\
          \           \"StringEquals\": \"open\",\n           \"Next\": \"GetSLAWaitTime\"\
          \n         },\n         {\n           \"Variable\": \"$.status\",\n    \
          \       \"StringEquals\": \"new\",\n           \"Next\": \"GetSLAWaitTime\"\
          \n         }\n       ],\n       \"Default\": \"ClosedOrNotNegative\"\n \
          \    },\n    \n     \"ClosedOrNotNegative\": {\n         \"Type\": \"Pass\"\
          ,\n         \"Result\": {\n           \"x-datum\": 1,\n           \"y-datum\"\
          : 1\n         },\n         \"ResultPath\": \"$.coords\",\n         \"End\"\
          : true\n       }\n                           \n   }\n }\n"
      RoleArn:
        Fn::GetAtt:
        - MyStatesExecutionRole
        - Arn
    Type: AWS::StepFunctions::StateMachine
  ZendeskEventBus:
    Properties:
      EventSourceName:
        Ref: EventSourceName
      Name:
        Ref: EventSourceName
    Type: AWS::Events::EventBus
Transform:
- AWS::Serverless-2016-10-31
