AWSTemplateFormatVersion: '2010-09-09'
Transform: 
- AWS::Serverless-2016-10-31
- AWS::CodeStar
Description: >
  sam-app
  Sample SAM Template for sam-app
  
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Zendesk-AWS-EventBridge
    Description: This application analyzes Zendesk tickets for negative sentiment, tags them as 'negative' and applies a customizable escalation time frame. It also translates tickets, finds keywords, and sends them to S3 for analysis.
    Author: Joe Norman
    SpdxLicenseId: MIT-0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['zendesk', 'moderation', 'sentiment', 'lambda','event Bridge','step functions', 'comprehend']
    HomePageUrl: https://github.com/joe-norman/eventbridge-zendesk
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/joe-norman/eventbridge-zendesk

  
##########################################################################
#  Code Star Params                                                      #
##########################################################################
Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''
##########################################################################
#  Lambda Environment Params: Zendesk Integration                        #
########################################################################## 
  ZenDeskUsernameKey:
    Description: Your agent username that will connect to the Zedesk API - email
    Type: AWS::SSM::Parameter::Value<String>
    Default: ZenDeskUsername
  ZenDeskTokenKey:
    Description: Your API Token
    Type: AWS::SSM::Parameter::Value<String>
    Default: ZenDeskToken
  ZenDeskDomainKey:
    Description: Your Unique Zendesk Domain name (excluding https:// and .com)
    Type: AWS::SSM::Parameter::Value<String>
    Default: ZenDeskDomain
##########################################################################
#  Lambda Environment Params : Escalation times                          #
########################################################################## 
  SLAUrgentWait:
    Description: Urgent priority SLA wait time in seconds
    Type: String
    Default: 120
  SLAHighWait:
    Description: High priority SLA wait time in seconds
    Type: String
    Default: 120
  SLANormalWait:
    Description: Normal priority SLA wait time in seconds
    Type: String
    Default: 120
##########################################################################
#  Lambda Environment Params : Analytics                       #
########################################################################## 
  S3_Bucket_Analytics:
    Description: S3 bucket name for dropping data used in Analytics
    Type: String
    Default: ''
##########################################################################
#  Event Bridge  Params : source name and acct ID                        #
########################################################################## 
  EventSourceName:
    Description: The event source name generated by the Zendesk connector
    Type: String
    Default: ''



Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:
##########################################################################
#  Lambda Functions                                                      #
##########################################################################
    ZenDeskDemoGetFullTicket:
        Type: AWS::Serverless::Function # Function Resource: 
        Properties:
            CodeUri: lambdas/getFullTicket
            Handler: getFullTicket.handler
            Runtime: nodejs10.x
            Role:
                Fn::GetAtt:
                - MyLambdaExecutionRole
                - Arn
            Environment:
                Variables:
                    ZenDeskUsername: !Ref ZenDeskUsernameKey
                    ZenDeskPassword: !Ref ZenDeskTokenKey
                    ZenDeskDomain: !Ref ZenDeskDomainKey
    ZenDeskDemoGetSentiment:
        Type: AWS::Serverless::Function # Function Resource: 
        Properties:
            CodeUri: lambdas/getSentiment
            Handler: getSentiment.handler
            Runtime: nodejs10.x
            Role:
                Fn::GetAtt:
                - MyLambdaExecutionRole
                - Arn
            Environment:
    ZenDeskDemoSetTags:
        Type: AWS::Serverless::Function # Function Resource: 
        Properties:
            CodeUri: lambdas/setTags
            Handler: setTags.handler
            Runtime: nodejs10.x
            Role:
                Fn::GetAtt:
                - MyLambdaExecutionRole
                - Arn
            Environment:
                Variables:
                    ZenDeskUsername: !Ref ZenDeskUsernameKey
                    ZenDeskPassword: !Ref ZenDeskTokenKey
                    ZenDeskDomain: !Ref ZenDeskDomainKey
    ZenDeskDemoSetPriority:
        Type: AWS::Serverless::Function # Function Resource: 
        Properties:
            CodeUri: lambdas/setPriority
            Handler: setPriority.handler
            Runtime: nodejs10.x
            Role:
                Fn::GetAtt:
                - MyLambdaExecutionRole
                - Arn
            Environment:
                Variables:
                    ZenDeskUsername: !Ref ZenDeskUsernameKey
                    ZenDeskPassword: !Ref ZenDeskTokenKey
                    ZenDeskDomain: !Ref ZenDeskDomainKey     
    ZenDeskDemoTranslateTicket:
        Type: AWS::Serverless::Function # Function Resource: 
        Properties:
            CodeUri: lambdas/translateTicket
            Handler: translateTicket.handler
            Runtime: nodejs10.x
            Role:
                Fn::GetAtt:
                - MyTranslateTextExecutionRole
                - Arn
    ZenDeskWriteToS3:
        Type: AWS::Serverless::Function # Function Resource: 
        Properties:
            CodeUri: lambdas/writeToS3
            Handler: writeToS3.handler
            Runtime: nodejs10.x
            Role:
                Fn::GetAtt:
                - MyWriteToS3ExecutionRole
                - Arn
            Environment:
                Variables:
                    S3_Bucket_Analytics: !Ref S3_Bucket_Analytics
##########################################################################
#   STEP FUNCTION                                                        #
##########################################################################
    ZendDemoStateMachine:
      Type: "AWS::StepFunctions::StateMachine"
      Properties:
        DefinitionString: !Sub |
                {
                   "Comment": "Understand the ticket sentiment, apply tags and check back when answered to ensure SLA's are met",
                   "StartAt": "FullTicketInfo",
                   "States": {

                     "FullTicketInfo": {
                       "Type" : "Task",
                       "Resource": "${ZenDeskDemoGetFullTicket.Arn}",
                       "InputPath":  "$.detail.ticket_event.ticket",
                       "ResultPath": "$",
                       "Next": "TranslateTicket"
                     },
                     
                     "TranslateTicket": {
                        "Type": "Task",
                        "Resource": "${ZenDeskDemoTranslateTicket.Arn",
                        "InputPath": "$",
                        "ResultPath": "$",
                        "OutputPath": "$",
                        "Next": "GetTopics"
                     },
                     
                     "GetTopics": {
                        "Type": "Task",
                        "Resource": "${ZenDeskDemoGetTopics.Arn",
                        "InputPath": "$",
                        "ResultPath": "$.topics",
                        "OutputPath": "$",
                        "Next": "GetSentiment"
                     },

                     "GetSentiment": {
                       "Type": "Task",
                       "Resource": "${ZenDeskDemoGetSentiment.Arn}",
                       "InputPath": "$.raw_subject",
                       "ResultPath": "$.sentiment",
                       "OutputPath": "$",
                       "Next": "WriteToS3"
                     },
                     
                     "WriteToS3": {
                       "Type": Task",
                       "Resource": "${ZenDeskDemoWriteToS3.Arn}",
                       "InputPath": "$",
                       "ResultPath": "$.sentToAnalytics",
                       "OutputPath": "$",
                       "Next": "isNegative"
                     },

                     "isNegative": {
                       "Type" : "Choice",
                       "Choices": [
                         {
                           "Variable": "$.sentiment.Sentiment",
                           "StringEquals": "NEGATIVE",
                           "Next": "FullTicketInfo"
                         }
                       ],
                       "Default": "ClosedOrNotNegative"
                     },
                 
                     "setTags": {
                       "Type" : "Task",
                       "Resource": "${ZenDeskDemoSetTags.Arn}",
                       "ResultPath": "$.tags",
                       "OutputPath": "$",
                       "Next": "isClosed"
                     },
                     
                     
                  "GetSLAWaitTime": {
                       "Type" : "Choice",
                       "Choices": [
                         {
                           "Variable": "$.priority",
                           "StringEquals": "normal",
                           "Next": "SLAHighWait"
                         },
                         {
                           "Variable": "$.priority",
                           "StringEquals": "high",
                           "Next": "SLAUrgentWait"
                         },
                         {
                           "Variable": "$.priority",
                           "StringEquals": "urgent",
                           "Next": "FinalEscalationState"
                         }
                       ],
                        "Default": "SLANormalWait"
                        
                     },
                     
                    "FinalEscalationState": {
                            "Comment" : "Ticket cannot be escalated further",
                            "Type": "Succeed"
                        },
                     
                     "EscalatePriority": {
                         "Type" : "Task",
                         "Resource": "${ZenDeskDemoSetPriority.Arn}",
                         "InputPath":  "$",
                         "ResultPath": "$",
                         "Next": "isClosed"
                     },

                     "SLANormalWait": {
                         "Type": "Wait",
                         "Seconds": ${SLANormalWait},
                         "Next": "EscalatePriority"
                       },
                       
                       "SLAHighWait": {
                         "Type": "Wait",
                         "Seconds": ${SLAHighWait},
                         "Next": "EscalatePriority"
                       },
                       
                       
                       "SLAUrgentWait": {
                         "Type": "Wait",
                         "Seconds":${SLAUrgentWait},
                         "Next": "EscalatePriority"
                       },

                     "isClosed": {
                       "Type" : "Choice",
                       "Choices": [
                         {
                           "Variable": "$.status",
                           "StringEquals": "open",
                           "Next": "GetSLAWaitTime"
                         },
                         {
                           "Variable": "$.status",
                           "StringEquals": "new",
                           "Next": "GetSLAWaitTime"
                         }
                       ],
                       "Default": "ClosedOrNotNegative"
                     },
                    
                     "ClosedOrNotNegative": {
                         "Type": "Pass",
                         "Result": {
                           "x-datum": 1,
                           "y-datum": 1
                         },
                         "ResultPath": "$.coords",
                         "End": true
                       }
                                           
                   }
                 }
        RoleArn: !GetAtt [ MyStatesExecutionRole, Arn ]
        
##########################################################################
#   Roles                                                                #
##########################################################################   

    MyLambdaExecutionRole:
        Description: Creating service role in IAM for AWS Lambda
        Type: AWS::IAM::Role
        Properties:
          RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}'
          AssumeRolePolicyDocument:
            Statement:
            - Effect: Allow
              Principal:
                Service: [lambda.amazonaws.com]
              Action: sts:AssumeRole
          Path: /
          ManagedPolicyArns:
            - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
            - !Sub 'arn:${AWS::Partition}:iam::aws:policy/ComprehendFullAccess'
    MyStatesExecutionRole:
        Type: "AWS::IAM::Role"
        Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow" 
                Principal:
                  Service:
                    - !Sub states.${AWS::Region}.amazonaws.com
                Action: "sts:AssumeRole"
          Path: "/"
          Policies:
            - PolicyName: StatesExecutionPolicy
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - "lambda:InvokeFunction"
                      - "comprehend:DetectSentiment"
                    Resource: "*"
    MyWriteToS3ExecutionRole:
        Description: Lambda service role to write to Analytics S3 Bucket
        Type: AWS::IAM::Role
        Properties:
          RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}-WriteToS3LambdaRole'
          AssumeRolePolicyDocument:
            Statement:
            - Effect: Allow
              Principal:
               Service: [lambda.amazonaws.com]
              Action: sts:AssumeRole
              Path: "/"
              ManagedPolicyArns:
                - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
              Policies:
                - PolicyName: WriteToS3ExecutionPolicy
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                     - Effect: Allow
                       Action:
                        - "s3:PutObject"
                       Resource: !Sub 'arn:aws:s3:::$(S3_Bucket_Analytics)'
    MyTranslateTextExecutionRole:
        Description: Lambda role for Translate Text function
        Type: AWS::IAM::Role
        Properties:
          RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}-TranslateTextLambdaRole'
          AssumeRolePolicyDocument:
            Statement:
            - Effect: Allow
              Principal:
                Service: [lambda.amazonaws.com]
              Action: sts:AssumeRole
          Path: /
          ManagedPolicyArns:
            - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
            - !Sub 'arn:${AWS::Partition}:iam::aws:policy/TranslateFullAccess'
##########################################################################
#   EVENT  BRIDGE                                                        #
##########################################################################
    ZendeskEventBus:
      Type: 'AWS::Events::EventBus'
      Properties:
        EventSourceName: !Ref EventSourceName
        Name: !Ref EventSourceName
    MyEventsRule:
      Type: 'AWS::Events::Rule'
      Properties:
        Description: Events Rule with StepFunctionParams
        EventBusName: !Ref EventSourceName
        EventPattern:
          account:
            - !Ref "AWS::AccountId"
          detail-type:
            - 'Support Ticket: Ticket Created'
        Targets:
          - Arn: >-
              !Ref ZendDemoStateMachine
            RoleArn: >-
              Fn::GetAtt:
                - MyStatesExecutionRole
                - Arn
            Id: NewTicketSFN
      DependsOn:
        - ZendeskEventBus
        - ZendDemoStateMachine
        - MyStatesExecutionRole